
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * convert tool from the resource data it found.  It
 * should not be modified by hand.
 * created time: 2012-12-06 19:18:59
 */
#ifndef __GENERATE_R_H__
#define __GENERATE_R_H__

class R
{
public:

    class string
    {
    public:
        const static unsigned int CONFIRM = 0;
        const static unsigned int CANCEL = 1;
    };
    
    class color
    {
    public:
        const static unsigned int FONT = 4294901760;
        const static unsigned int FONT_BORDER = 4278190080;
    };
    
    class scene
    {
    public:
        const static unsigned int CITY = 1137;
        const static unsigned int YEWAI = 37472;
    };
    
    class texture
    {
    public:
    };
    
    class patch_sprite
    {
    public:
        const static unsigned int UI_MAGICBG_UI_MAGICBG = 39665;
    };
    
    class music
    {
    public:
    };
    
    class ui
    {
    public:
    };
    
    class sprite
    {
    public:
        const static unsigned int CHARACTER_ACTORS_CHARATER = 18477;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC1 = 25409;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC10 = 32550;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC2 = 7943;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC3 = 58044;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC4 = 39873;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC5 = 23064;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC6 = 8322;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC7 = 58137;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC8 = 14643;
        const static unsigned int CHARACTER_ACTORS_CHARATER_NPC9 = 64883;
        const static unsigned int CHARACTER_ACTORS_FIGHT_SKILL = 4034;
        const static unsigned int CHARACTER_NPC_BIND = 13816;
        const static unsigned int CHARACTER_NPC_CSD = 24097;
        const static unsigned int CHARACTER_NPC_DEFALT = 21820;
        const static unsigned int CHARACTER_NPC_NPC_01 = 479;
        const static unsigned int CHARACTER_NPC_NPC_02 = 50836;
        const static unsigned int CHARACTER_NPC_NPC_03 = 35403;
        const static unsigned int CHARACTER_NPC_NPC_04 = 21596;
        const static unsigned int CHARACTER_NPC_NPC_05 = 4786;
        const static unsigned int CHARACTER_NPC_NPC_06 = 53771;
        const static unsigned int CHARACTER_NPC_NPC_07 = 38052;
        const static unsigned int CHARACTER_NPC_NPC_08 = 14545;
        const static unsigned int CHARACTER_NPC_NPC_09 = 64784;
        const static unsigned int CHARACTER_NPC_NPC_10 = 18248;
        const static unsigned int CHARACTER_NPC_NPC_100 = 51266;
        const static unsigned int CHARACTER_NPC_NPC_101 = 45728;
        const static unsigned int CHARACTER_NPC_NPC_102 = 4370;
        const static unsigned int CHARACTER_NPC_NPC_103 = 31616;
        const static unsigned int CHARACTER_NPC_NPC_11 = 35238;
        const static unsigned int CHARACTER_NPC_NPC_12 = 50808;
        const static unsigned int CHARACTER_NPC_NPC_13 = 1432;
        const static unsigned int CHARACTER_NPC_NPC_14 = 16447;
        const static unsigned int CHARACTER_NPC_NPC_15 = 33919;
        const static unsigned int CHARACTER_NPC_NPC_16 = 51437;
        const static unsigned int CHARACTER_NPC_NPC_17 = 2283;
        const static unsigned int CHARACTER_NPC_NPC_18 = 16766;
        const static unsigned int CHARACTER_NPC_NPC_19 = 32788;
        const static unsigned int CHARACTER_NPC_NPC_20 = 10731;
        const static unsigned int CHARACTER_NPC_NPC_21 = 60513;
        const static unsigned int CHARACTER_NPC_NPC_22 = 43625;
        const static unsigned int CHARACTER_NPC_NPC_23 = 26913;
        const static unsigned int CHARACTER_NPC_NPC_24 = 12770;
        const static unsigned int CHARACTER_NPC_NPC_25 = 63034;
        const static unsigned int CHARACTER_NPC_NPC_26 = 47582;
        const static unsigned int CHARACTER_NPC_NPC_27 = 31092;
        const static unsigned int CHARACTER_NPC_NPC_28 = 17497;
        const static unsigned int CHARACTER_NPC_NPC_29 = 664;
        const static unsigned int CHARACTER_NPC_NPC_30 = 43150;
        const static unsigned int CHARACTER_NPC_NPC_31 = 59629;
        const static unsigned int CHARACTER_NPC_NPC_32 = 44682;
        const static unsigned int CHARACTER_NPC_NPC_33 = 62120;
        const static unsigned int CHARACTER_NPC_NPC_34 = 10884;
        const static unsigned int CHARACTER_NPC_NPC_35 = 26817;
        const static unsigned int CHARACTER_NPC_NPC_36 = 42753;
        const static unsigned int CHARACTER_NPC_NPC_37 = 59905;
        const static unsigned int CHARACTER_NPC_NPC_38 = 16321;
        const static unsigned int CHARACTER_NPC_NPC_39 = 33880;
        const static unsigned int CHARACTER_NPC_NPC_40 = 37896;
        const static unsigned int CHARACTER_NPC_NPC_41 = 22238;
        const static unsigned int CHARACTER_NPC_NPC_42 = 5432;
        const static unsigned int CHARACTER_NPC_NPC_43 = 21329;
        const static unsigned int CHARACTER_NPC_NPC_44 = 3180;
        const static unsigned int CHARACTER_NPC_NPC_45 = 53347;
        const static unsigned int CHARACTER_NPC_NPC_46 = 37913;
        const static unsigned int CHARACTER_NPC_NPC_47 = 21584;
        const static unsigned int CHARACTER_NPC_NPC_48 = 4727;
        const static unsigned int CHARACTER_NPC_NPC_49 = 53524;
        const static unsigned int CHARACTER_NPC_NPC_50 = 33643;
        const static unsigned int CHARACTER_NPC_NPC_54 = 5325;
        const static unsigned int CHARACTER_NPC_NPC_55 = 21419;
        const static unsigned int CHARACTER_NPC_NPC_56 = 37245;
        const static unsigned int CHARACTER_NPC_NPC_61 = 13543;
        const static unsigned int CHARACTER_NPC_NPC_63 = 48544;
        const static unsigned int CHARACTER_NPC_NPC_64 = 30575;
        const static unsigned int CHARACTER_NPC_NPC_70 = 27184;
        const static unsigned int CHARACTER_NPC_NPC_71 = 44269;
        const static unsigned int CHARACTER_NPC_NPC_BAOXIANG = 10906;
        const static unsigned int CHARACTER_NPC_NPC_DENGLONG = 65496;
        const static unsigned int CHARACTER_NPC_NPC_DENGLONG01 = 56775;
        const static unsigned int CHARACTER_NPC_NPC_GONGJI = 25191;
        const static unsigned int CHARACTER_NPC_NPC_GOU = 25392;
        const static unsigned int CHARACTER_NPC_NPC_JIAOHUDIAN = 32733;
        const static unsigned int CHARACTER_NPC_NPC_KUANGSHI = 8612;
        const static unsigned int CHARACTER_NPC_NPC_PANLONGZHU = 14690;
        const static unsigned int CHARACTER_NPC_NPC_SHIMEN = 7644;
        const static unsigned int CHARACTER_NPC_NPC_XIAOJI = 1547;
        const static unsigned int CHARACTER_NPC_NPC_XINSUO = 16029;
        const static unsigned int CHARACTER_NPC_NPC_YUSHI = 58548;
        const static unsigned int UI_BUFF = 34926;
        const static unsigned int UI_BUILDINGICON = 20792;
        const static unsigned int UI_BUZHENBEIJING = 43019;
        const static unsigned int UI_DIANJI = 40747;
        const static unsigned int UI_FAGUANG = 47737;
        const static unsigned int UI_FRIENDLIST_BG = 65045;
        const static unsigned int UI_FRIENDLIST_FR = 12480;
        const static unsigned int UI_GUANKA = 39327;
        const static unsigned int UI_GUANKAFRONT = 53732;
        const static unsigned int UI_GUANKAGROUND = 62499;
        const static unsigned int UI_JINENG = 57793;
        const static unsigned int UI_LUEDUO = 22506;
        const static unsigned int UI_QJBM = 13313;
        const static unsigned int UI_SELECTMASK = 19394;
        const static unsigned int UI_UI_BATTLE = 8227;
        const static unsigned int UI_UI_BUILD = 54548;
        const static unsigned int UI_UI_CONSTRUCTION = 19459;
        const static unsigned int UI_UI_EFFECT = 13137;
        const static unsigned int UI_UI_ELEMENT = 10523;
        const static unsigned int UI_UI_FUBEN = 6553;
        const static unsigned int UI_UI_LOADING = 22575;
        const static unsigned int UI_UI_MAININTERFACE = 32371;
        const static unsigned int UI_UI_NEWCONSTRUCTION = 60891;
    };
    
};
#endif
