
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * convert tool from the resource data it found.  It
 * should not be modified by hand.
 * created time: 2012-12-14 12:33:49
 */
#ifndef __GENERATE_UI_H__
#define __GENERATE_UI_H__

class UI
{
public:

    class login
    {
    public:
        const static unsigned int PGAE_ID = 15640;
    
        const static unsigned int PATCH5 = 0;
        const static unsigned int PANEL6 = 1;
        const static unsigned int PANEL6_TEXT4 = 0;
        const static unsigned int PANEL6_INPUT5 = 1;
        const static unsigned int PANEL6_TEXT6 = 2;
        const static unsigned int PANEL6_INPUT7 = 3;
        const static unsigned int PANEL6_ANIMATION7 = 4;
        const static unsigned int PANEL6_TEXT9 = 5;
    };
    
    class loading
    {
    public:
        const static unsigned int PGAE_ID = 29922;
    
        const static unsigned int BG = 0;
        const static unsigned int BAR = 1;
        const static unsigned int PROGRESS = 2;
    };
    
    class main
    {
    public:
        const static unsigned int PGAE_ID = 31924;
    
        const static unsigned int PATCH0 = 0;
        const static unsigned int ANIMATION1 = 1;
        const static unsigned int ANIMATION10 = 2;
    };
    
};
#endif
