
/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * convert tool from the resource data it found.  It
 * should not be modified by hand.
 * created time: 2012-12-14 12:33:49
 */
#ifndef __GENERATE_UI_COMMAND_H__
#define __GENERATE_UI_COMMAND_H__

class UI_COMMAND
{
public:

    class login
    {
    public:
        const static short LOGIN = 513;
    };
    
    class loading
    {
    public:
    };
    
    class main
    {
    public:
        const static short HERO_PROPERTY = 514;
    };
    
    const static unsigned short MAX_COMMAND = 515;
};
#endif
